import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {Navbar, NavbarItem, NavbarContent, Link } from "@nextui-org/react"
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar isBordered className="bg-blue-950" position="static">
      <NavbarContent className="hidden sm:flex gap-10 px-4 py-4">
        <NavbarItem>
          <Link color="foreground" className="text-white" href="/">
            Home
          </Link>
        </NavbarItem>
      </NavbarContent>
      </Navbar>
        {children}</body>
    </html>
  );
}
